name: Playwright Tests

on: workflow_dispatch

jobs:
  test:
    timeout-minutes: 15
    runs-on: ${{ matrix.os }}
    strategy:
      # Prevent running in parallel
      max-parallel: 1
      matrix:
        # options (can be multiple) [ubuntu-latest, windows-latest, macos-latest]
        os: [windows-latest]

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 10.0.x # Match your project version
        
    - name: Install dotnet wasm tools
      run: dotnet workload install wasm-tools

    - name: Build Test
      run: dotnet build ./SpawnDev.BlazorJS.Tests/SpawnDev.BlazorJS.Tests.csproj

    - name: Install Playwright dependencies
      # Only needed on Linux
      if: ${{ runner.os == 'Linux' }}
      run: pwsh ./SpawnDev.BlazorJS.Tests/bin/Debug/net10.0/playwright.ps1 install-deps

    - name: Install Playwright
      run: pwsh ./SpawnDev.BlazorJS.Tests/bin/Debug/net10.0/playwright.ps1 install

      # Run test script
    - name: Set script exec bit
      shell: bash
      run: chmod +x ./SpawnDev.BlazorJS.Demo/_publish.sh
      
    - name: Set script exec bit
      shell: bash
      run: chmod +x ./SpawnDev.BlazorJS.Tests/_test.sh
      
      # Run test script
    - name: Start tests
      shell: bash
      run: ./SpawnDev.BlazorJS.Tests/_test.sh

    - name: Upload Playwright logs
      if: failure()
      uses: actions/upload-artifact@v4.3.2
      with:
        name: playwright
        retention-days: 2
        path: |
          ./SpawnDev.BlazorJS.Tests/bin/Debug/net10.0/playwright-traces/**/*.*
